### ISSUE TITLE
Can you atleast give RDIMO credit?

### ISSUE THREAD

**Issue by KingKDot** [hackirby/discord-injection#6]
Basically all discord injections including yours is based off his. You even left some of his function names the exact same thats how I knew let alone the config. He lowkey quit but ik he would still want his credit. His website is https://cheataway.com . If you need more proof about what I'm talking about lmk.

**Comment by hackirby** [comment]
You're right. I wrote the `discordPath` and `initiation` functions by copying code from another discord-injection repository. Since all Discord injections tend to copy from each other and there were no credits given, I wasn't aware that the code originated from Rdimo. I'll make sure to add proper credit to him.

Apart from these two functions, all the code is my own work. Additionally, I introduced new features, such as backup codes sniffing and devices request blocking, which I believe are original contributions.

I'm also going to refactor the two functions I copied to better match my JavaScript coding style. Don't worry, I'll make sure to keep the credits.

**Comment by KingKDot** [comment]
> You're right. I wrote the `discordPath` and `initiation` functions by copying code from another discord-injection repository. Since all Discord injections tend to copy from each other and there were no credits given, I wasn't aware that the code originated from Rdimo. I'll make sure to add proper credit to him.
> 
> 
> 
> Apart from these two functions, all the code is my own work. Additionally, I introduced new features, such as backup codes sniffing and devices request blocking, which I believe are original contributions.
> 
> 
> 
> I'm also going to refactor the two functions I copied to better match my JavaScript coding style. Don't worry, I'll make sure to keep the credits.

Oh yeah your fine ik it's weird asf I'm not calling u a skid or criticizing anything I think your code is very good I just wanted my homie to get credit. Good work tho.
